language: ruby
rvm:
- 2.3

script: ./scripts/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

deploy:
  provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: [stage, master]
