# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Philip House
email: phouse512 at gmail dot com
description: "A personal collection of thoughts on programming, learning, and other things."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://phizzle.space" # the base hostname & protocol for your site
github_username:  phouse512

# Build settings
markdown: kramdown
future: true

plugins: [jekyll-seo-tag]

collections:
- life_posts

stage: false
